'use client';

import React from 'react';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { MapPin, Mail, Phone, MessageSquare, Award, Clock } from 'lucide-react';
import { useLanguage } from '@/context/LanguageContext';

export default function CompanyPage() {
  const { language } = useLanguage(); const ja=language==='ja';
  const whatsappUrl='https://wa.me/818066651199?text=Hello%20SBA%20Automobile,%20I%20am%20contacting%20regarding%20vehicle%20export.';
  const facts=ja?[['会社名','SBA合同会社'],['事業名','SBA Automobile / SBA Transport Service'],['所在地','〒310-0832 茨城県水戸市吉田3066'],['主な事業','車両調達、国内取引、海外輸出、国内輸送のサポート']]:[['Company Name','SBA合同会社'],['Trade Names','SBA Automobile / SBA Transport Service'],['Address','〒310-0832 茨城県水戸市吉田3066, Mito, Ibaraki, Japan'],['Main Activities','Vehicle sourcing, domestic transactions, export and transport support']];
  return <div className="min-h-screen bg-obsidian-950 text-slate-100 flex flex-col selection:bg-japan-red selection:text-white"><Navbar/><main className="flex-1 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 w-full space-y-16">
    <div className="text-center max-w-3xl mx-auto"><div className="inline-flex items-center gap-2 mb-3"><span className="w-6 h-[2px] bg-japan-red"/><span className="text-xs uppercase tracking-[0.25em] text-japan-red font-bold">{ja?'会社情報':'Corporate Profile'}</span><span className="w-6 h-[2px] bg-japan-red"/></div><h1 className="text-4xl sm:text-5xl font-black text-white">SBA合同会社</h1><p className="text-sm text-japan-red font-semibold tracking-wider mt-1">SBA Automobile • SBA Transport Service</p><p className="text-sm text-slate-400 mt-3 leading-relaxed">{ja?'茨城県水戸市を拠点に、車両の購入・販売、海外輸出、国内輸送についてご相談いただけます。':'Based in Mito, Ibaraki, SBA合同会社 provides consultation and support for vehicle sourcing, domestic transactions, export and transport.'}</p></div>
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8"><div className="lg:col-span-8 glass-panel p-8 rounded-3xl border border-white/10 space-y-6"><h2 className="text-xl font-black text-white border-b border-white/10 pb-4">{ja?'会社概要':'Company Overview'}</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">{facts.map(([k,v])=><div key={k} className="bg-obsidian-900 p-4 rounded-xl border border-white/5"><span className="text-slate-400 block mb-1">{k}</span><span className="font-bold text-white text-sm">{v}</span></div>)}</div><div className="border-t border-white/10 pt-6 text-xs"><h3 className="text-sm font-bold text-white mb-2">{ja?'所在地':'Location'}</h3><p className="text-slate-300 leading-relaxed">{ja?'〒310-0832 茨城県水戸市吉田3066。お問い合わせ・お取引の窓口としてご利用いただけます。':'〒310-0832 Yoshida 3066, Mito, Ibaraki, Japan. Please use our contact channels for business and vehicle inquiries.'}</p></div></div>
      <div className="lg:col-span-4 space-y-6"><div className="glass-panel p-6 sm:p-8 rounded-3xl border border-white/15 space-y-4 text-xs"><h3 className="text-base font-bold text-white">{ja?'お問い合わせ':'Contact'}</h3><div className="space-y-3"><div className="flex items-start gap-3"><MapPin className="w-4 h-4 text-japan-red shrink-0"/><span className="text-slate-300">〒310-0832 茨城県水戸市吉田3066</span></div><div className="flex items-center gap-3"><Mail className="w-4 h-4 text-japan-red shrink-0"/><span className="text-slate-300">sbaautomobile.jp@gmail.com</span></div><div className="flex items-center gap-3"><Phone className="w-4 h-4 text-japan-red shrink-0"/><span className="text-slate-300">+81 80-6665-1199</span></div><div className="flex items-center gap-3"><Clock className="w-4 h-4 text-japan-red shrink-0"/><span className="text-slate-300">{ja?'営業時間はお問い合わせください':'Please contact us for current business hours'}</span></div></div><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="w-full py-3 px-4 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs flex items-center justify-center gap-2 shadow"><MessageSquare className="w-4 h-4"/>{ja?'WhatsAppで相談する':'WhatsApp Message'}</a></div><div className="glass-panel p-6 rounded-3xl border border-white/10 space-y-3 text-xs"><div className="flex items-center gap-2 text-japan-red font-bold"><Award className="w-4 h-4"/><span>{ja?'事業情報':'Business Information'}</span></div><p className="text-slate-400 leading-relaxed">{ja?'サービス内容、輸出条件、必要書類などは車両と仕向国の条件に応じて個別にご案内します。':'Service details, export conditions and required documents are discussed according to the vehicle and destination requirements.'}</p></div></div>
    </div></main><Footer/></div>;
}
