import { Vehicle, Inquiry } from '@/types';

export const INITIAL_DEMO_VEHICLES: Vehicle[] = [
  {
    id: 'demo-lc300-zx-2023',
    slug: 'toyota-land-cruiser-300-zx-2023',
    make: 'Toyota',
    model: 'Land Cruiser 300',
    trim: 'ZX 4WD (Modellista Aero)',
    year: 2023,
    mileage: 8400,
    engine: '3.5L V6 Twin-Turbo Petrol (V35A-FTS)',
    engineDisplacement: '3,444 cc',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    driveType: '4WD',
    chassisCode: '3BA-VJA300W',
    price: 11800000, // JPY (~$79,000 USD)
    currency: 'JPY',
    description: 'DEMO LISTING: Immaculate condition Toyota Land Cruiser 300 ZX with authentic Modellista Aero styling package. Premium Japanese domestic market specification. Features rear entertainment system, refrigerated cool box, multi-terrain monitor 360-degree camera system, panoramic sunroof, and full ventilated semi-aniline leather seating.',
    features: [
      'Authentic Modellista Aero Kit',
      'Panoramic Sunroof with Power Tilt',
      '360° Panoramic View Multi-Terrain Monitor',
      'Rear Seat Dual Entertainment Displays',
      'Ventilated & Heated Memory Seats',
      'JBL 14-Speaker Premium Sound System',
      'Center Console Refrigerated Cool Box',
      'Adaptive Variable Suspension (AVS)',
      'Toyota Safety Sense 3.0 with Radar Cruise'
    ],
    auctionGrade: 'Grade 5 / Interior A',
    steering: 'RHD',
    color: 'Precious White Pearl (090)',
    images: [
      'https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=85',
    ],
    status: 'available',
    featured: true,
    isDemo: true,
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'demo-gtr-nismo-2022',
    slug: 'nissan-gt-r-nismo-special-edition-2022',
    make: 'Nissan',
    model: 'GT-R',
    trim: 'Nismo Special Edition (VR38DETT)',
    year: 2022,
    mileage: 4200,
    engine: '3.8L V6 Twin-Turbocharged Handcrafted VR38DETT (600 HP)',
    engineDisplacement: '3,799 cc',
    transmission: 'DCT',
    fuelType: 'Petrol',
    driveType: 'AWD',
    chassisCode: '4BA-R35',
    price: 28500000, // JPY (~$190,000 USD)
    currency: 'JPY',
    description: 'DEMO LISTING: Rare collector opportunity. Genuine Japanese domestic Nismo Special Edition R35 GT-R featuring clear-coated carbon fiber engine hood, Rays 20-inch forged aluminum wheels with red rim accents, carbon ceramic Brembo brakes, and Recaro carbon bucket seats. Hand-assembled Takumi engine plaque.',
    features: [
      'Carbon Fiber Exposed Clear-Coated Hood',
      'Takumi Handcrafted 600HP VR38DETT',
      'Brembo Carbon Ceramic Brake System',
      'Exclusive Nismo Tuned Bilstein DampTronic',
      'Nismo Recaro Carbon-Backed Bucket Seats',
      'RAYS 20" Forged Lightweight Wheels',
      'Titanium Exhaust System with Sound Control',
      'Alcantara Wrapped Nismo Steering Wheel'
    ],
    auctionGrade: 'Grade 6 / Interior S (Like New)',
    steering: 'RHD',
    color: 'Stealth Gray (KAD)',
    images: [
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1600&q=85',
    ],
    status: 'available',
    featured: true,
    isDemo: true,
    createdAt: '2026-09-02T12:00:00.000Z',
    updatedAt: '2026-09-02T12:00:00.000Z',
  },
  {
    id: 'demo-civic-typer-fl5-2023',
    slug: 'honda-civic-type-r-fl5-2023',
    make: 'Honda',
    model: 'Civic Type R',
    trim: 'FL5 Championship White (6MT)',
    year: 2023,
    mileage: 6100,
    engine: '2.0L VTEC Turbo K20C1 (330 PS)',
    engineDisplacement: '1,996 cc',
    transmission: 'Manual',
    fuelType: 'Petrol',
    driveType: 'FWD',
    chassisCode: '6BA-FL5',
    price: 6400000, // JPY (~$43,000 USD)
    currency: 'JPY',
    description: 'DEMO LISTING: The benchmark front-wheel-drive sports car in iconic Championship White. Close-ratio 6-speed manual transmission with rev-matching system, active exhaust valve, Honda LogR performance telemetry system, and signature Type R red suede-style sport seats. Clean one-owner car from Kanagawa auction.',
    features: [
      '6-Speed Manual with Rev-Match System',
      'Honda LogR 2.0 Data Logger App Built-in',
      'Brembo 4-Piston Monobloc Front Calipers',
      'Signature Red Type R Bucket Seats & Carpet',
      '+R Race Track Drive Mode',
      'Die-Cast Aluminum Shift Knob',
      'Honda Sensing ADAS Suite',
      'Wireless Apple CarPlay & Android Auto'
    ],
    auctionGrade: 'Grade 5 / Interior A',
    steering: 'RHD',
    color: 'Championship White (NH0)',
    images: [
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1600&q=85',
    ],
    status: 'available',
    featured: true,
    isDemo: true,
    createdAt: '2026-09-03T08:00:00.000Z',
    updatedAt: '2026-09-03T08:00:00.000Z',
  },
  {
    id: 'demo-lexus-lx600-2023',
    slug: 'lexus-lx600-executive-2023',
    make: 'Lexus',
    model: 'LX 600',
    trim: 'Executive 4WD (4-Seater VIP)',
    year: 2023,
    mileage: 11200,
    engine: '3.5L V6 Twin-Turbo (V35A-FTS)',
    engineDisplacement: '3,444 cc',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    driveType: '4WD',
    chassisCode: '3BA-VJA310W',
    price: 18900000, // JPY (~$126,000 USD)
    currency: 'JPY',
    description: 'DEMO LISTING: Flagship luxury Japanese SUV in executive 4-passenger configuration. Rear VIP ottomans with shiatsu massage, rear touch-control console, Mark Levinson Reference 3D audio, active height control air suspension, and dual 11.6-inch rear HDMI screens. Ready for immediate worldwide shipping.',
    features: [
      'Ultra-Luxury 4-Seat Executive VIP Cabin',
      'Rear Reclining Ottomans with Shiatsu Massage',
      'Mark Levinson 25-Speaker Reference Audio',
      'Active Height Control (AHC) Hydraulic Suspension',
      'Dual 11.6" Rear Entertainment Displays',
      'BladeScan Adaptive LED Headlamps',
      'Fingerprint Authentication Push Start',
      'Soft-Close Vacuum Power Doors'
    ],
    auctionGrade: 'Grade 5 / Interior A',
    steering: 'RHD',
    color: 'Sonic Quartz (085)',
    images: [
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1541348263662-e0c8de4259ba?auto=format&fit=crop&w=1600&q=85',
    ],
    status: 'reserved',
    featured: false,
    isDemo: true,
    createdAt: '2026-09-03T14:30:00.000Z',
    updatedAt: '2026-09-03T14:30:00.000Z',
  },
  {
    id: 'demo-supra-rz-2022',
    slug: 'toyota-gr-supra-rz-manual-2022',
    make: 'Toyota',
    model: 'GR Supra',
    trim: 'RZ (6-Speed Manual)',
    year: 2022,
    mileage: 9500,
    engine: '3.0L Inline-6 Twin-Scroll Turbo (B58)',
    engineDisplacement: '2,997 cc',
    transmission: 'Manual',
    fuelType: 'Petrol',
    driveType: 'RWD',
    chassisCode: '3BA-DB06',
    price: 7200000, // JPY (~$48,000 USD)
    currency: 'JPY',
    description: 'DEMO LISTING: Toyota GR Supra RZ with the highly sought-after 6-speed intelligent Manual Transmission (iMT). Finished in vibrant Lightning Yellow with Black Alcantara/Leather interior, active differential, adaptive dampers, and Brembo front 4-piston calipers.',
    features: [
      '6-Speed Intelligent Manual Transmission (iMT)',
      'Active Electronic Differential',
      'Adaptive Variable Suspension (AVS)',
      'JBL 12-Speaker Surround Audio',
      'Head-Up Display (HUD)',
      '19" Forged Dual-Tone Alloy Wheels',
      'Carbon Fiber Center Console Trim'
    ],
    auctionGrade: 'Grade 4.5 / Interior B+',
    steering: 'RHD',
    color: 'Lightning Yellow',
    images: [
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1600&q=85',
    ],
    status: 'available',
    featured: false,
    isDemo: true,
    createdAt: '2026-09-04T09:15:00.000Z',
    updatedAt: '2026-09-04T09:15:00.000Z',
  },
  {
    id: 'demo-rx7-spirit-r-2002',
    slug: 'mazda-rx7-spirit-r-type-a-2002',
    make: 'Mazda',
    model: 'RX-7',
    trim: 'Spirit R Type-A (1 of 1,044)',
    year: 2002,
    mileage: 28400,
    engine: '1.3L Twin-Rotary Twin-Turbo (13B-REW)',
    engineDisplacement: '1,308 cc',
    transmission: 'Manual',
    fuelType: 'Petrol',
    driveType: 'RWD',
    chassisCode: 'GF-FD3S',
    price: 19800000, // JPY (~$132,000 USD)
    currency: 'JPY',
    description: 'DEMO LISTING: Legendary JDM icon. Ultimate final edition Spirit R Type-A FD3S RX-7. Factory red Recaro Kevlar bucket seats, BBS 17-inch Gunmetal wheels, drilled brake rotors, Bilstein sports suspension, and unmolested factory twin-turbo setup. Complete inspection documentation and export certificate ready.',
    features: [
      'Exclusive Factory Recaro Red Carbon-Kevlar Seats',
      'Original BBS Gunmetal Lightweight 17" Wheels',
      'Spirit R Numbered Interior Commemorative Plaque',
      'Factory Drilled Floating Disc Rotors',
      'Bilstein Factory Tuned Suspension',
      'Stainless Steel Brake Hoses',
      'Nardi Leather 3-Spoke Steering Wheel'
    ],
    auctionGrade: 'Grade 4.5 / Interior A (Collector Quality)',
    steering: 'RHD',
    color: 'Titanium Gray Metallic (25G)',
    images: [
      'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1600&q=85',
    ],
    status: 'sold',
    featured: false,
    isDemo: true,
    createdAt: '2026-09-04T16:00:00.000Z',
    updatedAt: '2026-09-04T16:00:00.000Z',
  },
];

export const INITIAL_DEMO_INQUIRIES: Inquiry[] = [
  {
    id: 'inq-demo-101',
    customerName: 'Marcus Vance',
    email: 'm.vance@vanceautomotive.co.uk',
    phone: '+44 7700 900123',
    country: 'United Kingdom',
    vehicleId: 'demo-lc300-zx-2023',
    vehicleTitle: '2023 Toyota Land Cruiser 300 ZX (Modellista Aero)',
    message: 'Hello SBA team, I am interested in exporting this Land Cruiser to Southampton port. Could you please provide a quotation including C&F shipping and JEVIC inspection?',
    status: 'new',
    createdAt: '2026-09-05T14:20:00.000Z',
  },
  {
    id: 'inq-demo-102',
    customerName: 'Kariuki Mwangi',
    email: 'kmwangi@nairobitrading.ke',
    phone: '+254 712 345678',
    country: 'Kenya',
    vehicleId: 'demo-lc300-zx-2023',
    vehicleTitle: '2023 Toyota Land Cruiser 300 ZX (Modellista Aero)',
    message: 'Looking for prompt shipment to Mombasa port. Please verify year of manufacture for Kenya 8-year import rule and confirm whether SBA Transport Service can handle port delivery.',
    status: 'contacted',
    createdAt: '2026-09-04T11:45:00.000Z',
  },
  {
    id: 'inq-demo-103',
    customerName: 'Liam Henderson',
    email: 'liam@hendersonsports.co.nz',
    phone: '+64 21 555 0192',
    country: 'New Zealand',
    vehicleId: 'demo-civic-typer-fl5-2023',
    vehicleTitle: '2023 Honda Civic Type R FL5 (Championship White)',
    message: 'Inquiring regarding roll-on/roll-off shipping to Auckland port. Please confirm if auction inspection sheet and de-registration certificate are available.',
    status: 'negotiating',
    createdAt: '2026-09-03T18:10:00.000Z',
  }
];
