'use client';

import React from 'react';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import Link from 'next/link';
import { ShoppingBag, ArrowRightLeft, Ship, Truck, CheckCircle2, ArrowRight } from 'lucide-react';
import { useLanguage } from '@/context/LanguageContext';

export default function ServicesPage() {
  const { language } = useLanguage();
  const ja = language === 'ja';
  const sections = ja ? [
    { id:'buy', icon:ShoppingBag, no:'01', title:'車両購入・調達サポート', desc:'日本国内のオークションや仕入れ先から、ご希望に合う車両を探すお手伝いをします。利用可能な車両情報やオークション書類を確認しながら進めます。', points:['車両・オークション情報の確認','必要に応じた検査・翻訳サポート','購入条件・費用を事前にご案内'], sideTitle:'対応内容', side:['在庫車両の確認','オークション車両の相談','希望車種・予算に応じた仕入れ相談'] },
    { id:'sell', icon:ArrowRightLeft, no:'02', title:'販売・買取相談', desc:'日本国内で車両の売却や取引を検討されている方からのご相談を受け付けています。車両情報とご希望の取引条件を確認してご案内します。', points:['車両情報の確認','売却・取引条件のご相談','必要書類についてご案内'], sideTitle:'ご相談時の情報', side:['車種・年式','走行距離・車両状態','車検・登録状況など'] },
    { id:'export', icon:Ship, no:'03', title:'海外輸出サポート', desc:'仕向国の要件に応じて、輸出手続き、必要書類、船積み方法などについてサポートします。Ro-Ro・コンテナなどの輸送方法もご相談いただけます。', points:['輸出関連書類のサポート','仕向国の要件に応じた確認','Ro-Ro・コンテナ輸送の相談'], sideTitle:'輸出について', side:['仕向国・到着港を確認','必要書類を確認','輸送方法・見積もりを相談'] },
    { id:'transport', icon:Truck, no:'04', title:'SBA Transport Service', desc:'オークション会場や保管場所から港までの車両輸送について、SBA Transport Serviceとして手配・調整をサポートします。', points:['国内車両輸送の手配','港までの輸送スケジュール調整','輸出手続きとの連携サポート'], sideTitle:'輸送について', side:['集荷場所を確認','希望港・スケジュールを確認','輸送条件を事前にご案内'] },
  ] : [
    { id:'buy', icon:ShoppingBag, no:'01', title:'Vehicle Sourcing & Purchase', desc:'We help locate vehicles through Japanese auctions and sourcing partners according to your requested model, year and budget. Available vehicle information and auction documentation can be reviewed where applicable.', points:['Vehicle and auction information review','Inspection and translation support when required','Purchase terms and costs explained in advance'], sideTitle:'Consultation Scope', side:['Available inventory review','Auction vehicle consultation','Sourcing by model and budget'] },
    { id:'sell', icon:ArrowRightLeft, no:'02', title:'Vehicle Sales & Purchase Consultation', desc:'If you are considering selling or trading a vehicle in Japan, contact SBA合同会社 to discuss the vehicle and transaction requirements.', points:['Vehicle information review','Sale and transaction consultation','Guidance on required documents'], sideTitle:'Useful Information', side:['Model and year','Mileage and condition','Inspection / registration status'] },
    { id:'export', icon:Ship, no:'03', title:'Worldwide Export Support', desc:'We support export procedures, required documentation and shipping arrangements according to the requirements of the destination country. Ro-Ro and container options can be discussed.', points:['Export-document support','Destination-country requirement review','Ro-Ro and container shipping consultation'], sideTitle:'Export Consultation', side:['Destination country and port','Required documents','Shipping method and quotation'] },
    { id:'transport', icon:Truck, no:'04', title:'SBA Transport Service', desc:'We coordinate vehicle transport from auction yards or storage locations to the port as part of the SBA Transport Service offering.', points:['Domestic vehicle transport coordination','Port delivery scheduling','Coordination with export procedures'], sideTitle:'Transport Consultation', side:['Collection location','Destination port and schedule','Transport conditions explained in advance'] },
  ];
  return <div className="min-h-screen bg-obsidian-950 text-slate-100 flex flex-col selection:bg-japan-red selection:text-white"><Navbar /><main className="flex-1 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 w-full space-y-20">
    <div className="text-center max-w-3xl mx-auto"><div className="inline-flex items-center gap-2 mb-3"><span className="w-6 h-[2px] bg-japan-red" /><span className="text-xs uppercase tracking-[0.25em] text-japan-red font-bold">{ja?'車両関連サービス':'Automotive Services'} </span><span className="w-6 h-[2px] bg-japan-red" /></div><h1 className="text-4xl sm:text-5xl font-black text-white uppercase tracking-tight">{ja?'サービス内容':'Our Services'}</h1><p className="text-sm text-slate-400 mt-3 leading-relaxed">{ja?'車両の購入・販売から海外輸出、国内輸送まで、ご要望に応じてサポートします。':'Support for vehicle sourcing, domestic transactions, export coordination and transport, arranged according to your requirements.'}</p></div>
    {sections.map((s,i)=>{const Icon=s.icon;return <div id={s.id} key={s.id} className="glass-panel p-8 sm:p-12 rounded-3xl border border-white/10 grid grid-cols-1 lg:grid-cols-12 gap-8 items-center"><div className={`lg:col-span-7 space-y-4 ${i%2?'order-2 lg:order-1':''}`}><div className="w-12 h-12 rounded-xl bg-japan-lacquer/40 border border-japan-red/40 flex items-center justify-center text-japan-red"><Icon className="w-6 h-6" /></div><span className="text-xs uppercase font-bold text-japan-red tracking-wider block">{ja?'サービス':'Service'} {s.no}</span><h2 className="text-3xl font-black text-white">{s.title}</h2><p className="text-sm text-slate-300 leading-relaxed">{s.desc}</p><ul className="space-y-2 text-xs text-slate-300 pt-2">{s.points.map((p)=><li key={p} className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-japan-red shrink-0" /><span>{p}</span></li>)}</ul></div><div className={`lg:col-span-5 bg-obsidian-900 p-6 rounded-2xl border border-white/10 space-y-3 text-xs ${i%2?'order-1 lg:order-2':''}`}><h3 className="text-sm font-bold text-white uppercase tracking-wider">{s.sideTitle}</h3><ul className="space-y-2 text-slate-400">{s.side.map((p)=><li key={p}>• {p}</li>)}</ul><Link href="/#inquiry" className="mt-4 w-full py-3 px-4 rounded-xl bg-japan-red hover:bg-red-700 text-white font-bold text-xs flex items-center justify-center gap-2 shadow"><span>{ja?'お問い合わせ':'Contact SBA'}</span><ArrowRight className="w-4 h-4" /></Link></div></div>})}
  </main><Footer /></div>;
}
